language: go

go:
  - 1.9.x
  - master

sudo: false

before_install:
  # Download and install dep
  - curl -sI https://github.com/golang/dep/releases/latest | grep -Fi Location  | tr -d '\r' | sed "s/tag/download/g" | awk -F " " '{ print $2 "/dep-linux-amd64"}' | wget --output-document=$GOPATH/bin/dep -i -
  - chmod +x $GOPATH/bin/dep
  # Install linters
  - go get github.com/mattn/goveralls
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

install:
  - dep ensure -v

script:
  - make
  - $HOME/gopath/bin/goveralls -service=travis-ci
